=== JoLuRe/XML-XSD/examen.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com" elementFormDefault="qualified">
  <xs:element name="quiz">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="question" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="type" maxOccurs="1" minOccurs="1">
                 <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="text"/>
                    <xs:enumeration value="select"/>
                    <xs:enumeration value="multiple"/>
                    <xs:enumeration value="radio"/>
                    <xs:enumeration value="checkbox"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element type="xs:string" name="title" maxOccurs="1" minOccurs="1"/>
              <xs:element type="xs:string" name="option" maxOccurs="unbounded" minOccurs="0"/>
              <xs:element type="xs:string" name="answer" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JoLuRe/XML-XSD/examen.xml
<?xml version="1.0" encoding="UTF-8"?>

<quiz
xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3schools.com examen.xsd">

<!-- free text type questions -->    

    <question id='item0'>
        <type>text</type>
        <title>1. Apellido de Marilyn</title>
        <answer>monroe</answer>
    </question>

<!-- single SELECT type questions -->    

    <question id='item1'>
        <type>select</type>
        <title>2. Medidas?</title>
        <option>a) 60-90-60</option>
        <option>b) 90-69-90</option> 
        <option>c) 90-60-90</option>
        <option>d) 96-69-96</option>        
        <answer>2</answer> <!-- 0, 1, 2, 3 -->
    </question>

<!-- select MULTIPLE type questions -->    

    <question id='item2'>
        <type>multiple</type>
        <title>3. Qué afirmaciones son ciertas?</title>
        <option>a) Su nombre era Norma Jeane Baker</option>
        <option>b) Cursó estudios de interpretación</option>
        <option>c) Participó en películas desde la más tierna infancia</option>
        <option>d) Murió a los 36 años</option>
        <option>e) Fue fiel a su marido a lo largo de toda su vida</option>
        <option>f) Rodó un cortometraje porno que la CIA encubrió</option>
        <option>g) Marlon Brando pagó por sus favores sexuales</option>
        <option>h) Sólo rodo una decena de películas</option>
        <answer>0</answer>
        <answer>3</answer>
        <answer>5</answer>
        <answer>6</answer>
    </question>

<!-- RADIO type questions -->     

    <question id='item3'>
        <type>radio</type>
        <title>4. Su escena más famosa</title>
        <option>a) Bus stop</option>
        <option>b) El Príncipe y la corista</option>
        <option>c) La tentación vive arriba</option>
        <option>d) Como atrapar a un millonario</option>
        <answer>2</answer>
    </question>    

<!-- CHECKBOX type questions -->   

    <question id='item4'>
        <type>checkbox</type>
        <title>5. Habilidades</title>
        <option>a) Cantante</option>
        <option>b) Actriz</option>
        <option>c) Modelo</option>
        <option>d) Presentadora de TV</option>
        <answer>0</answer>
        <answer>1</answer>
        <answer>2</answer>
    </question>    
    
<!-- free text type questions -->    

    <question id='item5'>
        <type>text</type>
        <title>6. Rubia, Morena o Pelirroja?</title>
        <answer>rubia</answer>
    </question>

<!-- single SELECT type questions -->    

    <question id='item6'>
        <type>select</type>
        <title>7. Nacionalidad?</title>
        <option>a) Sueca</option>
        <option>b) Americana</option>
        <option>c) Canadiense</option>
        <option>d) Emigrante rusa</option>
        <answer>1</answer> <!-- 0, 1, 2, 3 -->
    </question>
    
<!-- select MULTIPLE type questions -->    

    <question id='item7'>
        <type>multiple</type>
        <title>8. Mitos y leyendas</title>
        <option>a) Tuvo un affaire con JF Kennedy</option>
        <option>b) Tuvo un affaire con Robert Kennedy</option>
        <option>c) Sus orígenes son humildes</option>
        <option>d) Se casó 4 veces</option>
        <option>e) Sus restos descansan en su California natal</option>
        <option>f) Nunca posó desnuda</option>
        <option>g) Tuvo dos hijos</option>
        <option>h) Es poco conocido que tenía una hermana gemela</option>
        <answer>0</answer>
        <answer>1</answer>
        <answer>2</answer>
        <answer>4</answer>
    </question>
    
<!-- RADIO type questions -->     

    <question id='item8'>
        <type>radio</type>
        <title>9. Murió...</title>
        <option>a) De muerte natural</option>
        <option>b) Se suicidó</option>
        <option>c) En accidente tráfico</option>
        <option>d) Asesinada</option>
        <option>e) Aún vive</option>
        <answer>3</answer>
    </question>
    
<!-- CHECKBOX type questions -->   

    <question id='item9'>
        <type>checkbox</type>
        <title>10. Películas</title>
        <option>a) Solo ante el peligro</option>
        <option>b) Cumbres borrascosas</option>
        <option>c) La tentación vive arriba</option>
        <option>d) Los caballeros las prefieren rubias</option>
        <option>e) Con faldas y a lo loco</option>
        <answer>2</answer>
        <answer>3</answer>
    </question>    
    
</quiz>
